## Importing Libraries

In [1]:
# Data processing
import numpy as np 
import pandas as pd 

# Data visualization
import matplotlib.pyplot as plt 
import chart_studio
import chart_studio.plotly as py
import cufflinks as cf
import plotly.express as px
import plotly.graph_objects as go

# Make Plotly work in Jupyter Notebook
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)
# Use Plotly locally
cf.go_offline()

In [2]:
# Makes Jupyter Notebook cells wider
from IPython.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

# Print the full contents of each dataframe cell
pd.set_option('display.max_colwidth', None)

## Importing Data

In [3]:
WTTS_df = pd.read_excel('WTTS_Info.xlsx')
IMDB_df = pd.read_excel('Stargate_IMDB_Info.xlsx')

In [4]:
most_recent_reviewed_episode = 189

ratings_df = WTTS_df.iloc[:most_recent_reviewed_episode, :6]

In [5]:
ratings_df

,Episode_Total,Season_Num,Episode_Num,Title,Chevron_Ratings,Second_Chance
0,1,1,1,Children of the Gods,"4,4","6,4"
1,2,1,2,The Enemy Within,"2,5",NaN
2,3,1,3,Emancipation,"1,0.5","0,0"
3,4,1,4,The Broca Divide,"6,5",NaN
4,5,1,5,The First Commandment,"3,2.5",NaN
...,...,...,...,...,...,...
184,185,9,12,Collateral Damage,"4,4.5",NaN
185,186,9,13,Ripple Effect,"2,3.5",NaN
186,187,9,14,Stronghold,"4,4",NaN
187,188,9,15,Ethon,"7,6.5",NaN
188,189,9,16,Off the Grid,"7,7",NaN

## Data Transformation

In [6]:
# Convert strings to tuples 
ratings_df['Chevron_Ratings'] = ratings_df['Chevron_Ratings'].apply(lambda x: tuple(map(float, x.split(','))))

In [7]:
# Convert strings to tuples if not Null
ratings_df['Second_Chance'] = ratings_df['Second_Chance'].apply(lambda x: tuple(map(float, x.split(','))) if pd.notnull(x) else float('NaN'))

## Creating New Features

In [8]:
up_to_date_ratings = np.where(pd.isna(ratings_df['Second_Chance']), # If Second_Chance is Nan
                   ratings_df['Chevron_Ratings'], # select Chevron_Ratings
                   ratings_df['Second_Chance']) # otherwise select Second_Chance

# Extract first element of each ratings tuple into new column
ratings_df['Brent_Chevrons'] = [rating[0] for rating in up_to_date_ratings]

# Extract second element of each ratings tuple into new column
ratings_df['Zach_Chevrons'] = [rating[1] for rating in up_to_date_ratings]

In [9]:
# Create a column with the difference between the host's scores
ratings_df['Rating_Differential'] = abs(ratings_df['Brent_Chevrons'] - ratings_df['Zach_Chevrons'])

In [10]:
# Create a column with the IMDB ratings converted to chevrons
max = IMDB_df['Rating'].max()
min = IMDB_df['Rating'].min()
converted_ratings = (IMDB_df['Rating'] - min)/(max - min) * 8

ratings_df.insert(4, 'IMDB_Chevrons', converted_ratings.round(1))

In [11]:
ratings_df

,Episode_Total,Season_Num,Episode_Num,Title,IMDB_Chevrons,Chevron_Ratings,Second_Chance,Brent_Chevrons,Zach_Chevrons,Rating_Differential
0,1,1,1,Children of the Gods,5.0,"(4.0, 4.0)","(6.0, 4.0)",6.0,4.0,2.0
1,2,1,2,The Enemy Within,3.9,"(2.0, 5.0)",NaN,2.0,5.0,3.0
2,3,1,3,Emancipation,0.0,"(1.0, 0.5)","(0.0, 0.0)",0.0,0.0,0.0
3,4,1,4,The Broca Divide,2.5,"(6.0, 5.0)",NaN,6.0,5.0,1.0
4,5,1,5,The First Commandment,1.6,"(3.0, 2.5)",NaN,3.0,2.5,0.5
...,...,...,...,...,...,...,...,...,...,...
184,185,9,12,Collateral Damage,2.5,"(4.0, 4.5)",NaN,4.0,4.5,0.5
185,186,9,13,Ripple Effect,5.3,"(2.0, 3.5)",NaN,2.0,3.5,1.5
186,187,9,14,Stronghold,2.7,"(4.0, 4.0)",NaN,4.0,4.0,0.0
187,188,9,15,Ethon,3.7,"(7.0, 6.5)",NaN,7.0,6.5,0.5
188,189,9,16,Off the Grid,3.2,"(7.0, 7.0)",NaN,7.0,7.0,0.0

### Brent's Least Favorite Episodes

In [12]:
ratings_df.sort_values(by='Brent_Chevrons').head(14).reset_index()[['Season_Num', 'Episode_Num', 'Title', 'Brent_Chevrons']]

    Season_Num  Episode_Num               Title  Brent_Chevrons
0            1            3        Emancipation             0.0
1            3           13  The Devil You Know             2.0
2            2           10                Bane             2.0
3            2           13             Spirits             2.0
4            1           20            Politics             2.0
5            2           19      One False Step             2.0
6            8            5                Icon             2.0
7            5           20        The Sentinel             2.0
8            3            2                Seth             2.0
9            8            7            Affinity             2.0
10           1            8        Brief Candle             2.0
11           9           13       Ripple Effect             2.0
12           6           10                Cure             2.0
13           1            2    The Enemy Within             2.0

### Zach's Least Favorite Episodes

In [13]:
ratings_df.sort_values(by='Zach_Chevrons').head(12).reset_index()[['Season_Num', 'Episode_Num', 'Title', 'Zach_Chevrons']]

    Season_Num  Episode_Num                  Title  Zach_Chevrons
0            1            3           Emancipation            0.0
1            2           13                Spirits            2.0
2            2           10                   Bane            2.0
3            1           15                 Cor-ai            2.0
4            3            2                   Seth            2.0
5            2           19         One False Step            2.0
6            8            5                   Icon            2.0
7            6           16          Metamorphosis            2.5
8            2           22            Out of Mind            2.5
9            3            8                 Demons            2.5
10           1            5  The First Commandment            2.5
11           1           20               Politics            2.5

### Brent's Favorite Episodes

In [14]:
ratings_df.sort_values(by = 'Brent_Chevrons', ascending = False).head(7).reset_index()[['Season_Num', 'Episode_Num', 'Title', 'Brent_Chevrons']]

   Season_Num  Episode_Num                Title  Brent_Chevrons
0           6           22          Full Circle             8.0
1           2           15       The Fifth Race             8.0
2           6           12  Unnatural Selection             8.0
3           8           11               Gemini             8.0
4           8           20      Moebius: Part 2             8.0
5           8           19      Moebius: Part 1             8.0
6           5           21             Meridian             8.0

### Zach's Favorite Episodes

In [15]:
ratings_df.sort_values(by = 'Zach_Chevrons', ascending = False).head(12).reset_index()[['Season_Num', 'Episode_Num', 'Title', 'Zach_Chevrons']]

    Season_Num  Episode_Num              Title  Zach_Chevrons
0            6           22        Full Circle            8.0
1            5           12  Wormhole X-Treme!            8.0
2            8           18            Threads            8.0
3            2           15     The Fifth Race            8.0
4            7           22  Lost City: Part 2            8.0
5            7           21  Lost City: Part 1            8.0
6            7           18     Heroes: Part 2            8.0
7            8           20    Moebius: Part 2            8.0
8            7           17     Heroes: Part 1            8.0
9            8           19    Moebius: Part 1            8.0
10           6           19     The Changeling            8.0
11           5           21           Meridian            8.0

### How do Brent and Zach's scores compare over time?

In [16]:
# Create figure
fig = go.Figure(layout_yaxis_range=[0,8])

fig.add_trace(go.Scatter(x=ratings_df.index, y=ratings_df['Brent_Chevrons'].expanding().mean(), 
                        mode='lines', name='Brent', line=dict(color='#0096FF', width=2)))
fig.add_trace(go.Scatter(x=ratings_df.index, y=ratings_df['Zach_Chevrons'].expanding().mean(), 
                        mode='lines', name='Zach', line=dict(color='#FFA500', width=2)))
fig.add_trace(go.Scatter(x=ratings_df.index, y=ratings_df['IMDB_Chevrons'].expanding().mean(), 
                        mode='lines', name='IMDB', line=dict(color='#228B22', width=2)))

#Further style the figure
fig.update_layout(
    title='Average Chevron Ratings Over Time',
    xaxis_title='Episode Number', 
    yaxis_title='Rating',
    paper_bgcolor='#011222',
    font_color='#ffffff',
)

fig.show()

In [17]:
# Create figure
fig = go.Figure()

fig.add_trace(go.Scatter(x=ratings_df.index, y=ratings_df['Rating_Differential'].expanding().mean(), 
                        mode='lines', line=dict(color='#DA9100', width=2)))

#Further style the figure
fig.update_layout(
    title='Average Difference Between the Hosts\' Scores Over Time',
    xaxis_title='Episode Number', 
    yaxis_title='Score Difference',
    paper_bgcolor='#011222',
    font_color='#ffffff',
    showlegend= False,
)

fig.show()

### What episodes did Brent and Zach disagree on the most?

In [18]:
ratings_df.sort_values('Rating_Differential', ascending = False).head(11).reset_index()[['Season_Num', 'Episode_Num', 'Title', 'Brent_Chevrons', 'Zach_Chevrons', 'Rating_Differential']]

,Season_Num,Episode_Num,Title,Brent_Chevrons,Zach_Chevrons,Rating_Differential
0,4,15,Chain Reaction,3.0,7.0,4.0
1,7,6,Lifeboat,7.0,3.0,4.0
2,1,2,The Enemy Within,2.0,5.0,3.0
3,7,13,Grace,7.0,4.0,3.0
4,4,1,Small Victories,4.0,7.0,3.0
5,5,13,Proving Ground,7.0,4.0,3.0
6,7,15,Chimera,6.0,3.0,3.0
7,4,20,Entity,6.0,3.5,2.5
8,4,13,The Curse,3.0,5.5,2.5
9,6,16,Metamorphosis,5.0,2.5,2.5
10,5,5,Red Sky,7.0,4.5,2.5

## Season Long Ratings

In [19]:
seasons_df = ratings_df.groupby('Season_Num').mean(numeric_only=True)[['Brent_Chevrons', 'Zach_Chevrons', 'IMDB_Chevrons']]

In [20]:
# Create data for X-axis
seasons = list(seasons_df.index)

# Create data for Y-axis
Brent_ratings = seasons_df['Brent_Chevrons'].to_list()
Zach_ratings = seasons_df['Zach_Chevrons'].to_list()
IMDB_ratings = seasons_df['IMDB_Chevrons'].to_list()


############################
fig = go.Figure()

fig.add_trace(go.Bar(
    x = seasons,
    y = Brent_ratings,
    name = 'Brent',
    marker_color = '#0096FF'
))

fig.add_trace(go.Bar(
    x = seasons,
    y = Zach_ratings,
    name = 'Zach',
    marker_color = '#FFA500'
))

fig.add_trace(go.Bar(
    x = seasons,
    y = IMDB_ratings,
    name ='IMDB',
    marker_color = '#228B22'
))

fig.update_layout(
    title_text = 'Average Chevron Rating by Season', # title of plot
    xaxis_title_text = 'Season', # xaxis label
    yaxis_title_text = 'Average Chevron Rating', # yaxis label
    paper_bgcolor='#011222',
    font_color='#ffffff',
    bargap = 0.2, # gap between bars of adjacent location coordinates
    bargroupgap = 0.1 # gap between bars of the same location coordinates
)

fig.show()

## Working with Listener Predictions

In [21]:
# Create dataframe with predictions
predictions_df = WTTS_df.iloc[:most_recent_reviewed_episode, 6:]

# Convert predictions from stings to tuples
predictions_df = predictions_df.applymap(lambda x: tuple(map(float, x.split(','))) if isinstance(x, str) else x)

In [22]:
predictions_df

,Sean,Kevin,David,Paul,Kree Amisk,Rowan,Jen,LydiaAnn,JD,Adrian,...,Dustin,Luther,Cassidy,Letia,Fraiser,Kim,Mcjeston,Shawn,Arin,Mad Baron
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,"(4.0, 4.0)","(5.0, 4.0)","(3.0, 3.5)","(5.0, 5.0)","(3.0, 3.5)",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,NaN,"(6.0, 6.0)","(7.0, 7.0)",NaN,"(6.0, 6.5)",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,NaN,"(3.0, 3.0)","(4.0, 4.0)","(5.0, 5.5)","(4.0, 5.0)",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,"(3.0, 4.0)","(5.0, 5.0)","(7.0, 7.0)","(4.0, 4.5)","(4.0, 4.5)",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,"(4.0, 4.0)","(5.0, 5.0)","(4.0, 4.5)","(5.0, 5.5)","(5.0, 5.5)",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Number of Times Each Listener Has Correctly Predicted Both Ratings

In [23]:
# Create a dictionary with the correct number of guesses of each listener
listener_correct_guesses = {}

# Loop through every listener
for name in predictions_df.columns:
    
    # Loop through every prediction
    for index, prediction in enumerate(predictions_df[name]):
        
        # If prediction is available
        if type(prediction) is tuple:
            
            # If correctly predicted  scores
            if prediction[0] == ratings_df['Chevron_Ratings'].iloc[index][0] and prediction[1] == ratings_df['Chevron_Ratings'].iloc[index][1]:
                
                # If name already in dictionary
                if name in listener_correct_guesses:
                    # Add one to original scores
                    listener_correct_guesses[name] += 1
                else:
                    # Create entry with one correct guess
                    listener_correct_guesses[name] = 1
                    
                    
# Manually adding a correct score to David for 5.16.Summit/5.17.Last Stand
listener_correct_guesses['David'] += 1

# Print the dictionary
listener_correct_guesses

pd.DataFrame.from_dict(listener_correct_guesses, orient = 'index', columns = ['Correct_Predictions']).sort_values(['Correct_Predictions'], ascending = False)

                 Correct_Predictions
Sean                               9
David                              7
Aunt Susie                         4
Jacqueline                         4
Tim                                3
Rowan                              3
Jen                                3
LydiaAnn                           3
Kevin                              3
Dan                                2
Julie                              2
Sondes                             2
Caleb                              2
Austin                             1
Anna                               1
Letia                              1
Helio                              1
Chris                              1
Paula                              1
Tyrantosaurusex                    1
Carrie                             1
Justin                             1
Adrian                             1
JD                                 1
Kree Amisk                         1
Paul                               1
Mcjeston                           1